apiVersion: v1
appVersion: V1.0
description: '&quot;Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.&quot;'
name: commongroundnu
version: 0.1.0
home: www.commonground.nu
icon: www.commonground.nu